### ISSUE TITLE
unable to use pandas or numpy as it says...

### ISSUE THREAD

**Issue by cwing2019** [kluctl/go-embed-python#10]
I can run generate data folder and go &&python files.
(1) using extract from mylib\data\ failed
               fils,e:=embed_util.NewEmbeddedFiles(data.Data,"example2") 
		ep.AddPythonPath(fils.GetExtractedPath())  
   It throws e not xx file found
(2) 
directly use the lib like this
ep.AddPythonPath("C:\\Users\\Adminis\xx\\mylib\\data\\windows-amd64")

it says like this

ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Users\Administrator\AppData\Local\Temp\go-embedded-python-example-5f873ba0fa0239f0\python.exe"
  * The NumPy version is: "1.24.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by codablock** [comment]
This issue should be fixed now, as discussed in https://github.com/kluctl/go-embed-python/issues/20
