### ISSUE TITLE
error when run go generate ./...

### ISSUE THREAD

**Issue by longjin1991** [kluctl/go-embed-python#15]
I got an error:
ModuleNotFoundError: No module named 'ctypes'
when run comand:
go generate ./...
system: widows 11
go version: 1.20.1
image error:
![Screenshot 2023-03-06 160037](https://user-images.githubusercontent.com/23453308/223065017-305d3c0f-e8d8-4bbd-b702-746a8e7e16bc.png)

how to fix it.
thank you so much.

**Comment by codablock** [comment]
Windows as build system is untested and I unfortunately can't support this (I have no Windows)

**Comment by codablock** [comment]
I'm closing this. If someone wants to add support for Windows as build system, I'm happy to re-open it.
