### ISSUE TITLE
Choosing a python version

### ISSUE THREAD

**Issue by saul-data** [kluctl/go-embed-python#6]
Is it possible to choose the version of python?

**Comment by YugoCode** [comment]
@codablock Thanks for this awesome project! I'm also wondering how a specific Python version can be set, as a specific module I want to use doesn't support the latest versions of Python 🥺

**Comment by codablock** [comment]
This is somewhat related to https://github.com/kluctl/go-embed-python/issues/17#issuecomment-1502825888.

**Comment by codablock** [comment]
I have now automated the build workflow to build 3 versions of Python, from which you then can choose via the release tag. Please read the README.md for details on how release versions are built.
